- module: nginx

  access:
    enabled: true

    var.paths: ["/var/log/nginx/access.log"]

  error:
    enabled: true

    var.paths: ["/var/log/nginx/error.log"]

  ingress_controller:
    enabled: true

    var.paths: ["/var/log/nginx/nginx.log"]