- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Install gnupg
  ansible.builtin.apt:
    name: gnupg
    state: latest

- name: create sources.list
  copy: src=elasticrepo.list dest=/etc/apt/sources.list.d/elasticrepo.list

- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: http://elasticrepo.serveradmin.ru/elastic.asc
    state: present

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Install kibana
  ansible.builtin.apt:
    name: kibana
    state: latest
    
- name: create kibana.yml
  copy:
    content: |
      server.host: "{{ ansible_eth0.ipv4.address }}"
      server.publicBaseUrl: "http://{{ ansible_eth0.ipv4.address }}:5601/"
      logging:
        appenders:
          file:
            type: file
            fileName: /var/log/kibana/kibana.log
            layout:
              type: json
        root:
          appenders:
            - default
            - file
      pid.file: /run/kibana/kibana.pid
    dest: /etc/kibana/kibana.yml

- name: Make sure a service unit is running kibana
  ansible.builtin.systemd:
    state: started
    name: kibana
    enabled: yes
    daemon_reload: yes


    
